[package]
name = "velr"   
version = "0.1.0"
edition = "2021"
links = "velr"
build = "build.rs"

include = ["src/**", "build.rs", "prebuilt/**", "Cargo.toml", "LICENSE*"]

[dependencies]
arrow2 = { workspace = true, optional = true, default-features = false }
[dev-dependencies]
serde_json = "1"
[features]
default = []
arrow-ipc = ["dep:arrow2"]
